### ISSUE TITLE
Tagging/identifying vertices used during Voronoi mesh generation

### ISSUE THREAD

**Issue by measuredweighed** [Scrawk/Hull-Delaunay-Voronoi#1]
Thanks for the excellent library! I was wondering if it was currently possible to tag or ID vertices fed to a `VoronoiMesh2` instance to enable edges and regions to determine which raw vertex they relate to/were generated from.

I noticed the `Vertex2` class has an `Id` property but this doesn't seem to propagate.

**Comment by Scrawk** [comment]
You can use the ID but by default the generate function will automatically assign the id as the array index. 

To disable this pass false as the assign ids variable when calling generate. You must make sure all your ids are unique however.

You could also sub class vertex2 and provide your own id info.
