### ISSUE TITLE
Incremental Delaunay 

### ISSUE THREAD

**Issue by gviznyuk** [Scrawk/Hull-Delaunay-Voronoi#10]
Greetings,

How do I go about adding points to the delaunay triangulation incrementally with your implementation?

Thanks,
Georgii

**Comment by Scrawk** [comment]
You can’t. It’s not a incremental triangulator.

**Comment by gviznyuk** [comment]
Its not possible to make a few changes to update the simplexes with a addition of one more point?

**Comment by Scrawk** [comment]
It’s a lift based method. If you want to add a new point you have to re run the whole algorithm from the start. Lift methods are faster and generalise to any dimension of space easier but are not incremental.
