### ISSUE TITLE
Generating irregular (non-convex) meshes

### ISSUE THREAD

**Issue by Beril-1** [Scrawk/Hull-Delaunay-Voronoi#11]
Hello, 

I'd like to ask if it is possible to create irregular / non-convex meshes via Hull-Delaunay-Voronoi? By using Delaunay3D I can already create rectangular meshes. I would also like to create non-convex meshes such as U shape. I tried the ExampleVoronoi3D code with the vertex3 array that I defined. But it did not work or I did something wrong. I would be glad if you can help me with that.

Cheers,
Beril

**Comment by Scrawk** [comment]
Hi,

The boundary of a Delaunay triangulation is always convex so I dont think it can do want you need.
