### ISSUE TITLE
UpdateAdjacency method under Simplex.cs

### ISSUE THREAD

**Issue by gviznyuk** [Scrawk/Hull-Delaunay-Voronoi#2]
Greetings,

I have a java background, and I'm looking at the UpdateAdjacency  method with some confusion.
If you're resetting the tags to 0 and 1 at the beginning, won't the lv[j].Tag will be always be 0, and line 272 will force the method to exit?

Thanks,
Georgii

**Comment by Scrawk** [comment]
Its been a while since I looked at this but if the two simplex's share a vertex it will have its tag set to 1 at line 272. A vertex maybe in both the simplex's array of vertices.
