### ISSUE TITLE
DelaunayTriangulation3 and the 4th Dimension

### ISSUE THREAD

**Issue by gviznyuk** [Scrawk/Hull-Delaunay-Voronoi#4]
Greetings,

Can I ask why did you extend the 3rd dimension in the generate() method under DelaunayTriangulation3?

What will happen if just generate the convex hull using random points in the 3rd dimension?

Thanks,
Georgii

**Comment by Scrawk** [comment]
The triangulation is done using the lifting method. For a 3d triangulation this requires the convex hull in 4d to be calculated where the 4th value is the 3d positions squared distance from the origin.

It wont work if its not done in 4d.
